### ISSUE TITLE
Handle invalid property names in JSON

### ISSUE THREAD

**Issue by robfletcher** [robfletcher/grails-gson#22]
RIght now the deserializer will throw an exception if the JSON contains an invalid property name. Instead it should just be ignored (possibly with a warning log).

**Comment by matthurne** [comment]
I would certainly benefit from this improvement. I have a situation where I want to deserialize JSON using grails-gson where some of the data in the JSON is expected but is intentionally not represented on the domain class. At the moment, that results in an exception and failed deserialization. I would prefer that the extra data just be ignored.
