### ISSUE TITLE
Option to not lazy-load associations?

### ISSUE THREAD

**Issue by brian428** [robfletcher/grails-gson#26]
Not sure how easy or hard it would be to add, but I think it would be great to have an option where a Hibernate proxy that hasn't actually been loaded would just serialize the ID, rather than lazy load the proxy's data and serialize all of it. I did a lot of BlazeDS and Flex work in the past, and one of the biggest issues with BlazeDS was that it blindly loaded and serialized the entire object graph. So it was stunningly easy to send back an object and inadvertently end up loading and serializing a 10,000 node object graph.

**Comment by robfletcher** [comment]
I think this should be pretty easy to implement. Right now the serializer is detecting that an object is a `HibernateProxy` instance and resolving it. It should be easy to have a variant behavior there. Unresolved persistent collections might be tricky as I'm not sure the ids are available but I'll look into it.

In terms of serialization format do you have any preference between these two options?

``` json
{
    "name": "David Bowie",
    "albums": [
        {"id": 1}, {"id": 2}, {"id": 3}
    ]
}
```

or 

``` json
{
    "name": "David Bowie",
    "albums": [1, 2, 3]
}
```

I'd lean towards the former as it's simply a subset of the data that would be returned if the proxy were resolved.

**Comment by robfletcher** [comment]
Looking into this has revealed that the code I wrote for handling proxies is no longer being used due (presumably) to the refactoring I did recently. I can't seem to actually get hold of an unresolved proxy in my tests - they seem to be getting resolved automatically somehow.

**Comment by brian428** [comment]
On the format, yes, I'd also go with the first option, treating it as a subset. It could actually be useful if there were some way for the client to know that those instances are actually "proxies"...since a client could then write code that says "if someone is about to try and use this object, it's only a proxy, so go call the server and load the full object". Basically, client-side lazy loading. However, without injecting some arbitrary property (like _isProxy: true or something) I'm not sure how that could work, and not sure how I would feel about adding an artificial property to the data.

For detecting the Hibernate types, I'm looking at this, which is somewhat similar except it's an adapter for Flex AMF object serialization: https://code.google.com/p/dphibernate/source/browse/trunk/hibernateAdapter/src/net/digitalprimates/persistence/translators/hibernate/HibernateSerializer.java

No idea if something like that would help in your case but I thought I'd point to it just in case. It's basically checking for HibernateProxy, PersistentMap, AbstractPersistentCollection, and IHibernateProxy. You may want to make sure nothing is actually invoking the getter, since that would trigger hibernate to replace the proxy with the real object?

Thanks,

Brian

**Comment by brian428** [comment]
Oops, sorry, I closed the issue accidentally. I was going to add that maybe making a config option available to add something like _isProxy:true to the proxy objects would work. That way it would be something they could turn on by choice. Just an idea though, I don't want to pile on extra work. :-)

**Comment by robfletcher** [comment]
Burt Beckwith has pointed out to me that [this isn't going to be possible with collections](https://twitter.com/burtbeckwith/status/311497522126397441) which is probably the most useful scenario. Would it make sense to simply not include a collection property if it was proxied? (in the situation where the config says we shouldn't lazy-load)

**Comment by brian428** [comment]
I would say yes. Basically the real goal is to make it easy to stop the serializer from going crazy and loading up every related object all the way down the (potentially gigantic) object graph.

That said, not sure if you still want to mess with it, but the dphibernate folks seem to have gotten this to work with collections, though it takes a few additional steps: https://code.google.com/p/dphibernate/source/browse/trunk/hibernateAdapter/src/net/digitalprimates/persistence/translators/hibernate/HibernateSerializer.java#369

**Comment by robfletcher** [comment]
I have it basically working now. I need to fix up some unit tests as I'm now injecting a `org.codehaus.groovy.grails.support.proxy.ProxyHandler` instance into the `GrailsDomainSerializer` class.

It works as discussed for _n-to-one_ properties and skips _n-to-many_ properties if they are uninitialized proxies.

I'll get that committed & then take a look at that `HibernateSerializer` class & see if I can do something smarter with collections.

**Comment by brian428** [comment]
Great! Thanks. I just saw this blindside SO MANY people with BlazeDS that I don't want to see any Grails folks get hit by the same problem with GSON. :-)

**Comment by robfletcher** [comment]
I'm going to close this. We can open another issue for the variant collection handling.
