### ISSUE TITLE
unable to resolve class HttpConstants?

### ISSUE THREAD

**Issue by ghost** [robfletcher/grails-gson#29]
Steps to repro:
- install-gson-templates
- generate-controller Artist
- compile --> compilation error unable to resolve class grails.plugin.gson.http.HttpConstants

**Comment by robfletcher** [comment]
D'oh, I left that class in the test app instead of moving it into the plugin itself

**Comment by robfletcher** [comment]
This should be fixed in 1.1.1. Are you still having problems?
