### ISSUE TITLE
Cannot cast GrailsParameterMap to com.google.gson.JsonObject

### ISSUE THREAD

**Issue by sergiomichels** [robfletcher/grails-gson#30]
After installing the plugin it's not possible to set a domain properties with the values of GrailsParameterMap.

The issue can be reproduced in a controller or in a Integration Test

``` java
class Test {
  String name
}

class TestTests {
  @Test
  void setDomainProps() {
    Test tst = new Test(name: "x")
    assert tst.save(flush: true)
    MockHttpServletRequest request = RequestContextHolder.currentRequestAttributes().request
    request.setParameter("id", "1")
    request.setParameter("name", "My new name")

    Test.withSession { session ->
      session.flush()
      session.clear()

      GrailsParameterMap params = new GrailsParameterMap(request)
      //cannot cast object with class 'org.codehaus.groovy.grails.web.servlet.mvc.GrailsParameterMap' to class 'com.google.gson.JsonObject'
      tst.properties = params 
      assert teste.save(flush: true)
    }
  }
}
```

Probably due ArtefactEnhancer#enhanceDomains?

Grails 2.2.1, and also the test must be integration, unit test runs ok...

**Comment by robfletcher** [comment]
After much head scratching I've discovered that if you use

```
obj.setProperties(x)
```

then everything works as expected. Only the

```
obj.properties = x
```

syntax fails. As far as I was aware these were identical but it seems like the method dispatch has a subtle difference.

**Comment by robfletcher** [comment]
It looks like Groovy does not allow overloading of the `=` operator even though you _can_ overload `setProperties`. Unfortunately the last `setProperties` assigned will get used for the `=` operator no matter the argument type.

Here is a [Groovy web console script](http://groovyconsole.appspot.com/script/927001) that demonstrates the problem (see console output after executing).

**Comment by sergiomichels** [comment]
That was a tricky one. Thanks!!
