### ISSUE TITLE
Cannot install plugin

### ISSUE THREAD

**Issue by sakae-nakajima** [robfletcher/grails-gson#6]
Hi,

I am using Grails 2.1.0.

First of all, I could not install the plugin using the ZIP file I downloaded.
So, I attempted to created a plugin by myself using packge-plugin command.
Then, I encountered an error "GsonGrailsPlugin.groovy: 27: unable to resolve class ArtefactEnhancer ".

The class "ArtefactEnhancer" is in the test directory.
I moved this class to src directory, and it got packaged without any issue.

Regards,

**Comment by robfletcher** [comment]
Fixed now. ArtefactEnhancer was in the wrong place in the source tree. I have also released version 1.0-SNAPSHOT
